#! /bin/bash

XSH_SRC=${BASH_SOURCE[0]:-${(%):-%x}}
script_dir=$(cd "$(dirname "${XSH_SRC}")" &>/dev/null && pwd)
script_file=$(basename "${XSH_SRC}")

echo "#>> Script $script_file started at $(date +'%Z %Y-%m-%d %H:%M:%S')"

ALYX_CONTAINER_NAME=${1:-alyx_alyx}
POPULATE_CONTAINER_NAME=${2:-alyx_ingest_1}
SQL_DUMP_EXPIRES=${3:-3}

mkdir -p ~/.local/logs

err_exit() {
	set -e
	echo "#! Error: $*" >&2
	return 1
}

running_dcid() {
	[[ $# -lt 1 ]] && err_exit "Need at least the container name arg"
	local filt_list=(-f name="${1}" -f status=running)
	local filt
	shift
	if [[ $# -gt 0 ]]; then
		for filt in "$@"; do
			filt_list+=(-f $filt)
		done
	fi
	docker ps -a -q --no-trunc "${filt_list[@]}"
}

ALYX_CID=$(running_dcid $ALYX_CONTAINER_NAME)
echo "# INFO: Alyx container name: '$ALYX_CONTAINER_NAME'"
echo "# INFO: Alyx container id: '$ALYX_CID'"
[ -z "$ALYX_CID" ] && err_exit "Cannot find alyx container."

INGEST_CID=$(running_dcid $POPULATE_CONTAINER_NAME since=$ALYX_CID)
echo "# INFO: Populate/Ingest container name: '$POPULATE_CONTAINER_NAME'"
echo "# INFO: Populate/Ingest container id: '$INGEST_CID'"
[ -z "$INGEST_CID" ] && err_exit "Cannot find ingestion container."

echo "#> Ingestion jobs terminate started at $(date +'%Z %Y-%m-%d %H:%M:%S')"
docker exec -t $INGEST_CID ingest terminate
sleep 5

echo "#> Database reload started at $(date +'%Z %Y-%m-%d %H:%M:%S')"
docker exec -t $ALYX_CID alyx --reset_db_loaded_file fetch_and_reload_db

echo "#> Cleanup started at $(date +'%Z %Y-%m-%d %H:%M:%S')"
docker exec -t $ALYX_CID alyx --dump_exp=$SQL_DUMP_EXPIRES clean_dls
find ~/.local/logs/"${script_file}_"*.log -type f -mtime +14 -delete 2>/dev/null

echo "#<< Script $script_file finished at $(date +'%Z %Y-%m-%d %H:%M:%S')"
