python ingest_behavior.py
python analyses_behavior.py
python create_summary_csv.py
python compute_latest_date.py
python plotting_behavior.py
python insert_update_subject_last_date.py
python populate_daily_summary.py
