#! /bin/bash

export ALYX_ENTRY_ARGS=()

parse_entrypoint_args() {
	local arg
	if [[ $# -gt 0 ]]; then
		for arg in "$@"; do
			if [[ "${arg}" = "startserver" ]]; then
				echo "'startserver' is turned on by default"
			else
				ALYX_ENTRY_ARGS+=("${arg}")
			fi
		done
	fi
}

parse_entrypoint_args "$@"
ALYX_ENTRY_ARGS+=("startserver")

nohup alyx "${ALYX_ENTRY_ARGS[@]}" 2>&1 | tee -a /int-brain-lab/alyx_start_server.out &
alyx dev
